# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrix', '0006_auto_20170704_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='part_of',
            new_name='category',
        ),
    ]
